### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by frenck** [wroadd/hassio-addons#2]
# Problem/Motivation

I came here to notify you of a possible license violation.
You've forked my repository, which is perfectly fine. Nevertheless, the code in that repository is licensed under the MIT license.

The MIT license is a short and simple permissive license with conditions only requiring preservation of copyright and license notices. As it seems, these were removed from this fork recently.

## Proposed changes

Please restore the copyright and license notices as defined in the original license.

**Comment by wroadd** [comment]
Dear Franck, I will check it as I not planned to remove it.

Franck Nijhof <notifications@github.com> (időpont: 2017. okt. 10., K, 1:06)
ezt írta:

**Comment by wroadd** [comment]
Dear Franck,

I checked, I never removed the License.md file, and never planned it. Which others files did I removed that not should have?
